pipelines:
  default:
    - step:
        name: Bundling software
        script:
          - bash ./gradlew build installDist
        artifacts:
          - build/distributions/*.tar
          - build/install

  branches:
    release/*:
      - step:
          name: Bundling software
          caches:
            - gradle
          script:
            - bash ./gradlew build
          artifacts:
            - build/distributions/*.tar
            - build/layers/libs/*.jar
            - build/scripts
      - parallel:
        - step:
            name: Building AMD-64 image
            services:
              - docker
            script:
              - export `grep version gradle.properties`
              - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
              - docker build -t gjong/amd64-fintrack:$version --build-arg BASE_IMAGE=openjdk:15-oracle --build-arg BUILD_VERSION=$version .
              - docker push gjong/amd64-fintrack:$version
        - step:
            name: Building Windows Application
            caches:
              - gradle
              - node
            script:
              - bash ./gradlew buildElectron
              - pipe: atlassian/azure-storage-deploy:0.5.2
                variables:
                  SOURCE: build/bundle/*.exe
                  DESTINATION: 'https://jdocstorage.file.core.windows.net/$web/project/fintrack/'
                  DESTINATION_SAS_TOKEN: ${AZURE_STORAGE_JDOCSTORAGE_TOKEN}
            artifacts:
              - build/bundle/*.exe

definitions:
  services:
    docker:
      memory: 2048
