FROM ollama/ollama:0.5.11
ARG BUILD_VERSION
ARG JDK_VERSION
LABEL \
    maintainer="g.jongerius@jong-soft.com" \
    description="Ollama ${BUILD_VERSION}, custom image to support LLM in Pledger.io" \
    version="${BUILD_VERSION}"

# install the repository for eclipse JDK
RUN apt update \
    && apt install -y wget gpg curl \
    && wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null \
    && echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list

# install the correct version of the JDK
RUN apt update \
    && apt install -y temurin-${JDK_VERSION}-jre \
    && apt clean

ENV AI_MODEL=qwen2.5-coder:1.5b
ENV MICRAUT_PROFILES=ai
RUN mkdir -p /opt/scripts
COPY src/main/llm/entrypoint.sh /opt/scripts/entrypoint

ENTRYPOINT ["/opt/scripts/entrypoint"]

CMD ["/opt/scripts/prepare-ollama.sh"]
