name: Build electron

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string

jobs:
  native:
    name: Build for ${{ matrix.os }}
    if: ${{ inputs.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: build
      - name: Set Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Set version of project
        run: yarn version --new-version ${{ inputs.version }} --no-git-tag-version
      - name: Build native app
        run: yarn dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-app
          path: build/bundle/*.exe