name: Build electron

on:
  workflow_call:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string

jobs:
  native:
    name: Build for ${{ matrix.os }}
    if: ${{ inputs.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v6
      - name: Configure GraalVM
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'graalvm'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@11d4d83c63a6ce61b32d8a9c4faddbdb04fe9917
      - name: Compile native backend
        run: ./gradlew nativeCompile
        env:
          ORG_GRADLE_PROJECT_gpr_user: ${{ github.actor }}
          ORG_GRADLE_PROJECT_gpr_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Set version of project
        run: yarn version --new-version ${{ inputs.version }} --no-git-tag-version
      - name: Build desktop installer
        run: yarn dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: native-app
          path: build/bundle/*.exe
