name: Verify changes

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version
        id: set_version
        run: |
          VERSION=$(grep version gradle.properties | cut -d= -f2)
          echo "Version detected is ${VERSION}"
          echo "version=${VERSION}-SNAPSHOT" >> $GITHUB_OUTPUT
  build:
    needs: version
    uses: ./.github/workflows/build-artifact.yml
    with:
      version: ${{ needs.version.outputs.version }}
  native:
    needs: [version, build]
    uses: ./.github/workflows/build-native.yml
    with:
      version: ${{ needs.version.outputs.version }}
  deployment:
    needs: native
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: native-app
          path: build/bundle
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: build/bundle
          container_name: www
          connection_string: ${{ secrets.AZURE_CREDENTIALS }}
          extra_args: '--pattern *.exe'
