name: Release

on:
  release:
    types: [published]

permissions:
  packages: write


jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Set version
        id: set_version
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
  build:
    needs: version
    uses: ./.github/workflows/build-artifact.yml
    with:
      version: ${{ needs.version.outputs.version }}
  dockerize-llm:
    needs: [version, build]
    uses: ./.github/workflows/build-llm-container.yml
    with:
      version: ${{ needs.version.outputs.version }}
  dockerize:
    needs: [version, build]
    uses: ./.github/workflows/build-container.yml
    with:
      version: ${{ needs.version.outputs.version }}
  native:
    needs: [version, build]
    uses: ./.github/workflows/build-native.yml
    with:
      version: ${{ needs.version.outputs.version }}
  deployment:
    needs: native
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: native-app
          path: build/bundle
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: build/bundle
          container_name: $web
          connection_string: ${{ secrets.AZURE_CREDENTIALS }}
          extra_args: '--pattern *.exe'
